"""empty message

Revision ID: 51156f98f5dc
Revises: 
Create Date: 2019-03-21 13:48:15.915137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51156f98f5dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prime_line')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prime_line',
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('pn', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lot', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hanger', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts', name='prime_line_pkey')
    )
    # ### end Alembic commands ###
